In [68]:
import pandas as pd
import matplotlib as plt

df = pd.read_csv("/Users/talhamansari/diagnostic-equity-ml/projects/01-fairness-metrics/data/COMPASdata/propublicaCompassRecividism_data_fairml.csv/propublica_data_for_fairml.csv")
df.head(10)

,Two_yr_Recidivism,Number_of_Priors,score_factor,Age_Above_FourtyFive,Age_Below_TwentyFive,African_American,Asian,Hispanic,Native_American,Other,Female,Misdemeanor
0,0,0,0,1,0,0,0,0,0,1,0,0
1,1,0,0,0,0,1,0,0,0,0,0,0
2,1,4,0,0,1,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,1,0,1
4,1,14,1,0,0,0,0,0,0,0,0,0
5,0,3,0,0,0,0,0,0,0,1,0,0
6,0,0,0,0,0,0,0,0,0,0,1,1
7,0,0,0,0,0,0,0,0,0,0,0,0
8,1,3,1,0,1,1,0,0,0,0,0,1
9,0,0,0,0,0,0,0,0,0,0,1,1

In [72]:
df.shape

(6172, 12)

## Removing all entries that are not either White or Black

In [88]:
df = df[
(df["African_American"] == 1) | ((df["African_American"] == 0) & (df["Asian"] == 0) & (df["Hispanic"] == 0) & (df["Native_American"] == 0) & (df["Other"] == 0))
]

In [90]:
df.shape

(5278, 12)

## Splitting into two datasets, one black and one white

In [93]:
#since we removed all races except the two, we can assume all non Black entries are White

df_Black = df[df["African_American"] == 1]
df_White = df[df["African_American"] == 0]

In [95]:
df_Black

,Two_yr_Recidivism,Number_of_Priors,score_factor,Age_Above_FourtyFive,Age_Below_TwentyFive,African_American,Asian,Hispanic,Native_American,Other,Female,Misdemeanor
1,1,0,0,0,0,1,0,0,0,0,0,0
2,1,4,0,0,1,1,0,0,0,0,0,0
8,1,3,1,0,1,1,0,0,0,0,0,1
10,0,0,0,0,0,1,0,0,0,0,0,0
12,1,7,0,0,0,1,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
6165,1,0,0,0,0,1,0,0,0,0,0,1
6166,0,0,1,0,1,1,0,0,0,0,0,0
6167,0,0,1,0,1,1,0,0,0,0,0,0
6168,0,0,0,0,1,1,0,0,0,0,0,0
6170,0,3,0,0,0,1,0,0,0,0,1,1

In [97]:
df_White

,Two_yr_Recidivism,Number_of_Priors,score_factor,Age_Above_FourtyFive,Age_Below_TwentyFive,African_American,Asian,Hispanic,Native_American,Other,Female,Misdemeanor
4,1,14,1,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,0,0,0,1,1
7,0,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,0,0,0,0,0,0,1,1
11,1,1,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
6148,0,0,0,0,0,0,0,0,0,0,0,1
6151,0,0,0,0,0,0,0,0,0,0,0,0
6153,1,2,0,0,0,0,0,0,0,0,1,1
6158,0,0,1,0,1,0,0,0,0,0,0,0
6164,1,0,1,0,1,0,0,0,0,0,0,1

## Now finding false positives (FPR) via the following formula:
$$FPR = \frac{FP}{FP + TN}$$

Where FP is the number of false positives (predicted by algorithm to re-offend, and did not re-offend), and TN is true negatives (predicted by algorithm to not re-offend, and did not re-offend).

In [105]:
FP_Black = len(df_Black[(df_Black["Two_yr_Recidivism"] == 0) & (df_Black["score_factor"] == 1)])
TN_Black = len(df_Black[(df_Black["Two_yr_Recidivism"] == 0) & (df_Black["score_factor"] == 0)])

FPR_Black = FP_Black/(FP_Black + TN_Black)
FPR_Black

0.4233817701453104

In [107]:
FP_White = len(df_White[(df_White["Two_yr_Recidivism"] == 0) & (df_White["score_factor"] == 1)])
TN_White = len(df_White[(df_White["Two_yr_Recidivism"] == 0) & (df_White["score_factor"] == 0)])

FPR_White = FP_White/(FP_White + TN_White)
FPR_White

0.22014051522248243